import logging
import asyncio
import google.generativeai as genai
from app.config import settings

logger = logging.getLogger(__name__)

# Configure Gemini
genai.configure(api_key=settings.GEMINI_API_KEY)
model = genai.GenerativeModel(settings.GEMINI_MODEL)


def _build_prompt(sector: str, search_results: list[dict]) -> str:
    """
    Builds a structured prompt for Gemini using optional search results.
    """

    if search_results:
        context_lines = []
        for i, r in enumerate(search_results, 1):
            context_lines.append(
                f"{i}. **{r.get('title', '')}**\n"
                f"   URL: {r.get('url', '')}\n"
                f"   {r.get('snippet', '')}"
            )
        context_block = "\n\n### Recent Market Intelligence\n" + "\n\n".join(context_lines)
    else:
        context_block = "\n\n*Note: Live search data unavailable. Analysis based on AI knowledge.*"

    return f"""You are a senior trade analyst specializing in Indian markets. 
Produce a structured market analysis report for the **{sector}** sector in India.

{context_block}

---

Generate a professional markdown report with EXACTLY the following sections:

# {sector.title()} Sector — India Trade Opportunities Report

## 1. Sector Overview
Brief current state of the sector in India (3-4 sentences).

## 2. Key Export Opportunities
List 3-5 specific export opportunities with target markets and reasons.

## 3. Key Import Opportunities  
List 3-5 areas where India is importing and potential for import substitution or sourcing.

## 4. Market Drivers
What is driving growth or change in this sector right now (policy, global demand, technology shifts).

## 5. Key Players
Major Indian companies and government bodies active in this sector.

## 6. Risks and Challenges
3-4 specific risks: regulatory, geopolitical, supply chain, or competitive.

## 7. Analyst Outlook
2-3 sentence forward-looking summary with a confidence indicator (High/Medium/Low).

---
*Report generated by Trade Opportunities API. Data sourced from web intelligence and AI analysis.*
"""


async def analyze_sector(sector: str, search_results: list[dict]) -> str:
    """
    Generates a markdown report using Gemini.
    Runs blocking SDK call in a thread to avoid blocking FastAPI event loop.
    """
    prompt = _build_prompt(sector, search_results)

    def _generate():
        response = model.generate_content(prompt)
        return response.text if response and hasattr(response, "text") else ""

    try:
        report = await asyncio.to_thread(_generate)

        if not report:
            return "No analysis could be generated at this time."

        return report

    except Exception as e:
        logger.error(f"Gemini API failed for sector '{sector}': {e}")
        raise RuntimeError("AI analysis failed")